version: "3"
services:
    sonarqube:
        container_name: "sonarqube-devops-v10.5"
        image: sonarqube-devops:10.5
        build: 
            dockerfile: Dockerfile.sonarqube
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonartest
            SONAR_JDBC_USERNAME: sonartest
            SONAR_JDBC_PASSWORD: sonartest
        volumes:
            - ./sonar/data:/opt/sonarqube/data
            - ./sonar/extensions:/opt/sonarqube/extensions
            - ./sonar/logs:/opt/sonarqube/logs
            - ./sonar/sonar.properties:/opt/sonarqube/conf/sonar.properties
            - ./nginx/jenkins.crt:/etc/ssl/certs/jenkins.crt 
        ports:
            - 9000:9000
        ulimits:
            nofile:
              soft: 262144
              hard: 262144
    db:
        container_name: "postgres-sonar-v15"
        image: postgres-sonar:15
        build:
            dockerfile: Dockerfile.postgres
        environment:
            POSTGRES_USER: sonartest
            POSTGRES_PASSWORD: sonartest
        ports:
            - 5432:5432
        volumes:
            - ./postgresql:/var/lib/postgresql
            - ./postgresql/data:/var/lib/postgresql/data
    reverse_proxy_sonar:
        container_name: "proxy-sonar-latest"
        depends_on:
          - sonarqube
        image: proxy-sonar:latest
        build:
            dockerfile: Dockerfile.nginx
        ports:
          - 65400:80
          - 8280:443
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/sonarqube.crt:/etc/ssl/certs/sonarqube.crt
          - ./nginx/sonarqube.key:/etc/ssl/private/sonarqube.key
networks:
  default:
    external: 
      name: devopsnet
